// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNativeWebsocket = require("react-native-websocket");

function make(url, onOpen, onMessage, onError, onClose, reconnect, children) {
  return ReasonReact.wrapJsForReason(ReactNativeWebsocket.default, {
              url: url,
              onOpen: onOpen,
              onMessage: onMessage,
              onError: onError,
              onClose: onClose,
              reconnect: reconnect
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
